### ISSUE TITLE
master since release has important fixes, and HA should bump the version

### ISSUE THREAD

**Issue by gdt** [rhasspy/webrtc-noise-gain#21]
The last release is more than 6 months ago, and there are fixes on master since then:
```
38a6d1e Add armv6/armv7 docker builds
a5ea46f setup.py: Include other BSDs in elif clause matching freebsd
f938874 Fix compile on musl
30a7ebe Fix build on FreeBSD.
```

These take the module from not working to working on all the BSDs, and seem very low risk for other platforms.

Could you tag e.g. 1.2.4?  That would allow bumping the version in HA.

**Comment by gdt** [comment]
Looks like we have an actual release!

Is there an HA PR to bump the version of webrtc-noise-gain?

**Comment by synesthesiam** [comment]
webrtc has been dropped in favor of microVAD: https://github.com/home-assistant/core/pull/122861

**Comment by gdt** [comment]
Thanks for pointing that out.  Well, that's unfortunate, and I guess we can move on to seeing if microVAD has portability bugs :-(

Thanks for being cooperative about handling BSD patches.

**Comment by synesthesiam** [comment]
I expect there to be far fewer portability bugs.

The codebase is less complex than WebRTC since it's only doing VAD, and I haven't needed to adjust any flags yet when compiling across Linux amd64/arm64/armv7/armv6 and macOS. I still need to build Windows wheels though.

**Comment by gdt** [comment]
On NetBSD 10, I just created a venv and did `bin/pip install pymicro-vad` which completed quickly and uninterestingly, so things are looking good.  Thanks for the encouragement.
